import React, { useEffect, useState } from "react";
import { Plus, Upload } from "lucide-react";
import * as XLSX from "xlsx";
import { api } from "../lib/api";
import { Empty, PageHead } from "../components/ui";
export default function Masters({ refresh }) {
  const [masters, setMasters] = useState({ quality: [], party: [], company: [] }), [tab, setTab] = useState("quality"), [name, setName] = useState(""), [msg, setMsg] = useState("");
  const load = () => Promise.all(["quality", "party", "company"].map((x) => api("/masters/" + x))).then((v) => setMasters({ quality: v[0], party: v[1], company: v[2] }));
  useEffect(() => { load(); }, [refresh]);
  const add = async () => { if (!name.trim()) return; try { await api("/masters/" + tab, { method: "POST", body: JSON.stringify({ name }) }); setName(""); setMsg("Added successfully"); load(); } catch (e) { setMsg(e.message); } };
  const del = async (id) => { if (confirm("Remove this master value?")) { await api("/masters/" + tab + "/" + id, { method: "DELETE" }); load(); } };
  const importExcel = (e) => { const file = e.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = async (ev) => { const wb = XLSX.read(ev.target.result, { type: "array" }), data = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], { header: 1 }).flat().map((x) => String(x || "").trim()).filter(Boolean); let added = 0; for (const value of data) { try { await api("/masters/quality", { method: "POST", body: JSON.stringify({ name: value }) }); added++; } catch {} } setMsg(`${added} qualities imported`); load(); }; reader.readAsArrayBuffer(file); e.target.value = ""; };
  const label = tab === "quality" ? "Quality" : tab === "party" ? "Party" : "Company";
  return <div className="content"><PageHead title="Master Data" desc="Control the dropdown values used throughout your workspace." action={tab === "quality" ? <label className="btn"><Upload size={15} /> Import Quality Excel<input hidden type="file" accept=".xlsx,.xls,.csv" onChange={importExcel} /></label> : null} /><div className="master-layout"><div className="master-tabs">{[["quality", "Quality / Product"], ["party", "Party"], ["company", "Company"]].map(([x, text]) => <button className={tab === x ? "active" : ""} onClick={() => { setTab(x); setMsg(""); }} key={x}>{text}<span>{masters[x].length}</span></button>)}</div><div className="panel master-panel"><div className="inline-add"><input className="input" value={name} onChange={(e) => setName(e.target.value)} onKeyDown={(e) => e.key === "Enter" && add()} placeholder={`Add ${label} name`} /><button className="btn primary" onClick={add}><Plus size={15} /> Add</button></div>{msg && <div className="alert info">{msg}</div>}<div className="master-list">{masters[tab].map((x) => <div className="master-item" key={x._id}><span>{x.name}</span><button onClick={() => del(x._id)}>Remove</button></div>)}{!masters[tab].length && <Empty title="No values" text="Add your first master value above." />}</div></div></div><div className="notice"><b>Quality design:</b> Quality stores the product name only. Multiple shades belong to stock transactions, so one quality can safely have many shades and lots.</div></div>;
}
