import React, { useEffect, useState } from "react";
import { ArrowLeft, BarChart3, CheckCircle2, Factory, Package } from "lucide-react";
import { api } from "../lib/api";
import { DataTable, fmtDate, kg, Loading, Metric, num } from "../components/ui";
export default function QualityDetail({ id, onBack }) {
  const [d, setD] = useState(null), [tab, setTab] = useState("beams");
  useEffect(() => { api("/analytics/quality/" + id).then(setD); }, [id]);
  if (!d) return <Loading />;
  return <div className="content"><button className="back" onClick={onBack}><ArrowLeft size={16} /> Back to inventory</button><div className="detail-hero"><div><div className="eyebrow">QUALITY INVENTORY</div><h2>{d.quality.name}</h2><p>Trace received yarn through lots, shades and produced beams.</p></div><div className="detail-total"><span>Remaining</span><strong>{kg(d.remainingWeight)}</strong></div></div><div className="metrics compact"><Metric label="Received" value={kg(d.receivedWeight)} icon={Package} /><Metric label="Used in Beams" value={kg(d.usedWeight)} icon={Factory} /><Metric label="Remaining" value={kg(d.remainingWeight)} icon={BarChart3} /><Metric label="Beams" value={num(d.beams.length)} icon={CheckCircle2} /></div><div className="tabs"><button className={tab === "beams" ? "active" : ""} onClick={() => setTab("beams")}>Beam Inventory</button><button className={tab === "stock" ? "active" : ""} onClick={() => setTab("stock")}>Source Stock</button></div>{tab === "beams" ? <DataTable headers={["Beam No.", "Date", "Challan", "Party", "Ends", "Meter", "Denier", "Weight", "Width", "Pipes"]} rows={d.beams.map((b) => [b.beamNo, fmtDate(b.date), b.challanNo, b.party?.name, num(b.ends), num(b.meter), b.finalDenier, kg(b.beamWeight), b.width || "—", b.pipes || "—"])} /> : <DataTable headers={["Date", "Challan", "Party", "Company", "Shade", "Lot", "Boxes", "Cones", "Net Weight"]} rows={d.stocks.map((s) => [fmtDate(s.date), <b>{s.challanNo}</b>, s.party?.name, s.company?.name, s.shadeNo, s.lotNo || "—", num(s.box), num(s.totalCones), kg(s.netWeight)])} />}</div>;
}
