import React, { useEffect, useState } from "react";
import { Plus } from "lucide-react";
import { api } from "../lib/api";
import { DataTable, Field, FormError, kg, Modal, ModalActions, num, PageHead, SelectField, Toolbar } from "../components/ui";

function StockModal({ masters, onClose, onSaved }) {
  const [f, setF] = useState({ date: new Date().toISOString().slice(0, 10), challanNo: "", quality: "", party: "", company: "", box: 0, totalCones: 0, netWeight: "", shadeNo: "", lotNo: "", remarks: "" }), [err, setErr] = useState("");
  const set = (k, v) => setF((previous) => ({ ...previous, [k]: v }));
  const save = async (e) => { e.preventDefault(); try { await api("/stock", { method: "POST", body: JSON.stringify({ ...f, box: Number(f.box), totalCones: Number(f.totalCones), netWeight: Number(f.netWeight) }) }); onSaved(); } catch (e) { setErr(e.message); } };
  return <Modal title="New Stock Entry" subtitle="Add incoming yarn to the selected quality, shade and lot." onClose={onClose}><FormError text={err} /><form onSubmit={save}><div className="formgrid"><Field label="Date"><input className="input" type="date" value={f.date} onChange={(e) => set("date", e.target.value)} /></Field><Field label="Challan No."><input required className="input" value={f.challanNo} onChange={(e) => set("challanNo", e.target.value)} /></Field><SelectField label="Quality" value={f.quality} set={(v) => set("quality", v)} options={masters.quality} /><SelectField label="Party Name" value={f.party} set={(v) => set("party", v)} options={masters.party} /><SelectField label="Company" value={f.company} set={(v) => set("company", v)} options={masters.company} /><Field label="Shade No."><input required className="input" value={f.shadeNo} onChange={(e) => set("shadeNo", e.target.value)} /></Field><Field label="Box"><input className="input" type="number" min="0" value={f.box} onChange={(e) => set("box", e.target.value)} /></Field><Field label="Total Cones"><input className="input" type="number" min="0" value={f.totalCones} onChange={(e) => set("totalCones", e.target.value)} /></Field><Field label="Net Weight (KG)"><input required className="input" type="number" step="0.001" min="0" value={f.netWeight} onChange={(e) => set("netWeight", e.target.value)} /></Field><Field label="Lot No."><input className="input" value={f.lotNo} onChange={(e) => set("lotNo", e.target.value)} /></Field><Field label="Remarks" full><textarea className="textarea" rows="3" value={f.remarks} onChange={(e) => set("remarks", e.target.value)} /></Field></div><ModalActions onClose={onClose} label="Save Stock Entry" /></form></Modal>;
}
export default function Stock({ refresh }) {
  const [rows, setRows] = useState([]), [masters, setMasters] = useState({ quality: [], party: [], company: [] }), [open, setOpen] = useState(false), [q, setQ] = useState(""), [loading, setLoading] = useState(true);
  const load = () => Promise.all([api("/stock"), ...["quality", "party", "company"].map((x) => api("/masters/" + x))]).then(([r, ...m]) => { setRows(r); setMasters({ quality: m[0], party: m[1], company: m[2] }); }).finally(() => setLoading(false));
  useEffect(() => { load(); }, [refresh]);
  const filtered = rows.filter((r) => `${r.challanNo} ${r.quality?.name} ${r.party?.name} ${r.shadeNo} ${r.lotNo}`.toLowerCase().includes(q.toLowerCase()));
  return <div className="content"><PageHead title="Stock Entry" desc="Receive yarn into inventory and keep every lot traceable." action={<button className="btn primary" onClick={() => setOpen(true)}><Plus size={15} /> New Stock Entry</button>} /><Toolbar value={q} onChange={setQ} placeholder="Search challan, quality, party, shade…" /><DataTable headers={["Date", "Challan", "Quality", "Party", "Company", "Shade", "Lot", "Boxes", "Cones", "Net Weight"]} rows={filtered.map((r) => [r.date && new Date(r.date).toLocaleDateString("en-IN"), <b>{r.challanNo}</b>, r.quality?.name, r.party?.name, r.company?.name, r.shadeNo, r.lotNo || "—", num(r.box), num(r.totalCones), <b>{kg(r.netWeight)}</b>])} loading={loading} empty="No stock entries found." />{open && <StockModal masters={masters} onClose={() => setOpen(false)} onSaved={() => { setOpen(false); load(); }} />}</div>;
}
